sources:
  - id: ibm_careers
    name: IBM Careers
    type: dynamic
    country: Germany
    url: https://careers.ibm.com
    note: "Requires Playwright (JS-heavy)"

  - id: example_greenhouse
    name: Airbnb (Greenhouse)
    type: static
    country: Germany
    url: https://boards.greenhouse.io/airbnb
    selectors:
      job_card: "div.opening"
      title: "a"
      location: "span.location, span.location.inline"
      link: "a"
